---

pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success=continuous-integration/travis-ci/pr
    actions:
      merge:
        method: merge
        strict: true
