---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: snapscheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      name: SnapScheduler
  template:
    metadata:
      labels:
        name: SnapScheduler
    spec:
      serviceAccountName: snapscheduler
      containers:
        - name: snapscheduler
          image: quay.io/backube/snapscheduler:latest
          command:
            - SnapScheduler
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "SnapScheduler"
